// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  pilots: create.doc("pilots", {"index.mdx": () => import("../content/pilots/index.mdx?collection=pilots"), "freemium-playbook/index.mdx": () => import("../content/pilots/freemium-playbook/index.mdx?collection=pilots"), "agent-os/index.mdx": () => import("../content/pilots/agent-os/index.mdx?collection=pilots"), "freemium-playbook/build-1/index.mdx": () => import("../content/pilots/freemium-playbook/build-1/index.mdx?collection=pilots"), "freemium-playbook/build-1/module-1.mdx": () => import("../content/pilots/freemium-playbook/build-1/module-1.mdx?collection=pilots"), "freemium-playbook/build-1/module-2.mdx": () => import("../content/pilots/freemium-playbook/build-1/module-2.mdx?collection=pilots"), "freemium-playbook/build-1/module-3.mdx": () => import("../content/pilots/freemium-playbook/build-1/module-3.mdx?collection=pilots"), "freemium-playbook/build-1/module-4.mdx": () => import("../content/pilots/freemium-playbook/build-1/module-4.mdx?collection=pilots"), "freemium-playbook/build-2/index.mdx": () => import("../content/pilots/freemium-playbook/build-2/index.mdx?collection=pilots"), "freemium-playbook/build-2/module-5.mdx": () => import("../content/pilots/freemium-playbook/build-2/module-5.mdx?collection=pilots"), "freemium-playbook/build-2/module-6.mdx": () => import("../content/pilots/freemium-playbook/build-2/module-6.mdx?collection=pilots"), "freemium-playbook/build-2/module-7.mdx": () => import("../content/pilots/freemium-playbook/build-2/module-7.mdx?collection=pilots"), "freemium-playbook/build-2/module-8.mdx": () => import("../content/pilots/freemium-playbook/build-2/module-8.mdx?collection=pilots"), "freemium-playbook/build-2/module-9.mdx": () => import("../content/pilots/freemium-playbook/build-2/module-9.mdx?collection=pilots"), "agent-os/build-1/index.mdx": () => import("../content/pilots/agent-os/build-1/index.mdx?collection=pilots"), "agent-os/build-1/module-1.mdx": () => import("../content/pilots/agent-os/build-1/module-1.mdx?collection=pilots"), "agent-os/build-1/module-2.mdx": () => import("../content/pilots/agent-os/build-1/module-2.mdx?collection=pilots"), "agent-os/build-1/module-3.mdx": () => import("../content/pilots/agent-os/build-1/module-3.mdx?collection=pilots"), "agent-os/build-1/module-4.mdx": () => import("../content/pilots/agent-os/build-1/module-4.mdx?collection=pilots"), "agent-os/build-1/module-5.mdx": () => import("../content/pilots/agent-os/build-1/module-5.mdx?collection=pilots"), }),
};
export default browserCollections;